import type { ModelOption, ModelCapability, ModelProvider } from "../core/types.js";

// ─── Providers ─────────────────────────────────────────────────────
export const PROVIDERS: Record<string, ModelProvider> = {
  ollama: {
    id: "ollama",
    name: "Ollama (Local)",
    type: "local",
    baseUrl: process.env.OLLAMA_BASE_URL || "http://localhost:11434",
  },
  openrouter: {
    id: "openrouter",
    name: "OpenRouter",
    type: "cloud",
    baseUrl: "https://openrouter.ai/api/v1",
    apiKeyEnv: "OPENROUTER_API_KEY",
  },
  anthropic: {
    id: "anthropic",
    name: "Anthropic Direct",
    type: "cloud",
    baseUrl: "https://api.anthropic.com/v1",
    apiKeyEnv: "ANTHROPIC_API_KEY",
  },
  google: {
    id: "google",
    name: "Google AI",
    type: "cloud",
    baseUrl: "https://generativelanguage.googleapis.com/v1beta",
    apiKeyEnv: "GOOGLE_AI_API_KEY",
  },
  openai: {
    id: "openai",
    name: "OpenAI",
    type: "cloud",
    baseUrl: "https://api.openai.com/v1",
    apiKeyEnv: "OPENAI_API_KEY",
  },
};

// ─── Model Pricing Table (per 1K tokens, USD) ─────────────────────
// Prices as of early 2026. Update regularly.
export const MODEL_OPTIONS: ModelOption[] = [
  // ── Local (Free) ──
  {
    provider: PROVIDERS.ollama,
    model: "llama3.2-vision:11b",
    inputCostPer1k: 0,
    outputCostPer1k: 0,
    capabilities: ["text-generation", "vision", "analysis"],
    qualityScore: 62,
    latencyMs: 800,
  },
  {
    provider: PROVIDERS.ollama,
    model: "qwen2.5-vl:7b",
    inputCostPer1k: 0,
    outputCostPer1k: 0,
    capabilities: ["text-generation", "vision", "code-generation"],
    qualityScore: 60,
    latencyMs: 600,
  },
  {
    provider: PROVIDERS.ollama,
    model: "deepseek-coder-v2:16b",
    inputCostPer1k: 0,
    outputCostPer1k: 0,
    capabilities: ["code-generation", "text-generation", "analysis"],
    qualityScore: 72,
    latencyMs: 1200,
  },
  {
    provider: PROVIDERS.ollama,
    model: "glm-4.7-flash",
    inputCostPer1k: 0,
    outputCostPer1k: 0,
    capabilities: ["text-generation", "code-generation", "analysis"],
    qualityScore: 58,
    latencyMs: 400,
  },
  // ── OpenRouter (Cloud) ──
  {
    provider: PROVIDERS.openrouter,
    model: "anthropic/claude-sonnet-4",
    inputCostPer1k: 0.003,
    outputCostPer1k: 0.015,
    capabilities: ["text-generation", "code-generation", "vision", "analysis"],
    qualityScore: 92,
    latencyMs: 2000,
  },
  {
    provider: PROVIDERS.openrouter,
    model: "anthropic/claude-haiku-3.5",
    inputCostPer1k: 0.0008,
    outputCostPer1k: 0.004,
    capabilities: ["text-generation", "code-generation", "vision", "analysis"],
    qualityScore: 82,
    latencyMs: 800,
  },
  {
    provider: PROVIDERS.openrouter,
    model: "google/gemini-2.0-flash",
    inputCostPer1k: 0.0001,
    outputCostPer1k: 0.0004,
    capabilities: ["text-generation", "code-generation", "vision", "analysis"],
    qualityScore: 78,
    latencyMs: 600,
  },
  {
    provider: PROVIDERS.openrouter,
    model: "google/gemini-2.0-pro",
    inputCostPer1k: 0.00125,
    outputCostPer1k: 0.005,
    capabilities: ["text-generation", "code-generation", "vision", "analysis"],
    qualityScore: 88,
    latencyMs: 3000,
  },
  {
    provider: PROVIDERS.openrouter,
    model: "deepseek/deepseek-chat-v3",
    inputCostPer1k: 0.00027,
    outputCostPer1k: 0.0011,
    capabilities: ["text-generation", "code-generation", "analysis"],
    qualityScore: 80,
    latencyMs: 1500,
  },
  {
    provider: PROVIDERS.openrouter,
    model: "meta-llama/llama-3.3-70b",
    inputCostPer1k: 0.0005,
    outputCostPer1k: 0.0008,
    capabilities: ["text-generation", "code-generation", "analysis"],
    qualityScore: 76,
    latencyMs: 1200,
  },
  // ── Direct Anthropic ──
  {
    provider: PROVIDERS.anthropic,
    model: "claude-sonnet-4-20250514",
    inputCostPer1k: 0.003,
    outputCostPer1k: 0.015,
    capabilities: ["text-generation", "code-generation", "vision", "analysis"],
    qualityScore: 92,
    latencyMs: 1800,
  },
  // ── Direct Google ──
  {
    provider: PROVIDERS.google,
    model: "gemini-2.0-flash",
    inputCostPer1k: 0.0001,
    outputCostPer1k: 0.0004,
    capabilities: ["text-generation", "code-generation", "vision", "analysis"],
    qualityScore: 78,
    latencyMs: 500,
  },
  // ── Image Generation (cost per image, stored as cost per 1k "tokens" = 1 image) ──
  {
    provider: PROVIDERS.openrouter,
    model: "midjourney/v6",
    inputCostPer1k: 0.04,
    outputCostPer1k: 0,
    capabilities: ["image-generation"],
    qualityScore: 95,
    latencyMs: 30000,
  },
  {
    provider: PROVIDERS.openrouter,
    model: "nanobanana-3-pro",
    inputCostPer1k: 0.01,
    outputCostPer1k: 0,
    capabilities: ["image-generation"],
    qualityScore: 82,
    latencyMs: 15000,
  },
  // ── Video Generation ──
  {
    provider: PROVIDERS.openrouter,
    model: "google/veo-3.1",
    inputCostPer1k: 0.05,
    outputCostPer1k: 0,
    capabilities: ["video-generation"],
    qualityScore: 90,
    latencyMs: 120000,
  },
  {
    provider: PROVIDERS.openrouter,
    model: "kling/v2",
    inputCostPer1k: 0.03,
    outputCostPer1k: 0,
    capabilities: ["video-generation"],
    qualityScore: 85,
    latencyMs: 90000,
  },
  {
    provider: PROVIDERS.openrouter,
    model: "luma/dream-machine",
    inputCostPer1k: 0.025,
    outputCostPer1k: 0,
    capabilities: ["video-generation"],
    qualityScore: 80,
    latencyMs: 60000,
  },
  // ── Audio ──
  {
    provider: PROVIDERS.openrouter,
    model: "elevenlabs/v2",
    inputCostPer1k: 0.015,
    outputCostPer1k: 0,
    capabilities: ["audio-generation", "voice-cloning"],
    qualityScore: 92,
    latencyMs: 5000,
  },
  {
    provider: PROVIDERS.openrouter,
    model: "suno/v4",
    inputCostPer1k: 0.02,
    outputCostPer1k: 0,
    capabilities: ["audio-generation"],
    qualityScore: 88,
    latencyMs: 45000,
  },
];
